ember-animation/ember-animated

- addon/components/animated-container.js
- addon/debug.js
- addon/motion.js
- addon/motions/follow.js
- addon/motions/move.js
- addon/motions/opacity.js
- addon/motions/resize.js
- addon/motions/scale.js
- addon/sprite.js
- addon/transition-context.js
- addon/transitions/move-over.js
- tests/dummy/app/components/animated-text.js
- tests/dummy/app/components/each-example.js
- tests/dummy/app/components/swapping-lists-example.js
- tests/dummy/app/components/two-lists-example.js
- tests/dummy/app/controllers/direct-style.js
- tests/dummy/app/controllers/here-there.js
- tests/dummy/app/controllers/hero/detail.js
- tests/dummy/app/controllers/hero/index.js
- tests/dummy/app/controllers/inline-text.js
- tests/dummy/app/controllers/nested.js
- tests/dummy/app/controllers/orphan.js
- tests/integration/components/animated-each-test.js
- tests/integration/components/animated-orphans-test.js
- tests/unit/move-test.js
- tests/unit/opacity-test.js
- this makes it clearer that normal function composition works and is good
- less total noise in transitions
- move some conventional boilerplate (new Motion) into motions themselves, so that callers don't need it
- drop the need for animate() on transition context by putting run() on Motion
deb904f
> Api reform

- package.json
- yarn.lock
The new testing APIs need at least v4.2.0, and the `package.json` was still allowing versions below that.
/cc @ef4
> Update `ember-cli-qunit` to v4.3.2

- config/ember-try.js
- ember-cli-build.js
- package.json
- tests/dummy/app/templates/components/bind-example.hbs
- tests/dummy/app/templates/components/swapping-lists-example.hbs
- tests/dummy/app/templates/components/two-lists-example.hbs
- tests/dummy/app/templates/demos/here-there.hbs
Thanks mostly to @cibernox's hard work we have nearly everything working without jQuery.
The final issue is that there are some acceptance tests that use checkbox, and apparently Ember's own checkbox component depends on jQuery until [very recently](https://github.com/emberjs/ember.js/commit/a233625150b484ae473e0c590f6e3efade1f4658).
> removes jQuery from the tests & demo app

- ember-cli-build.js
- package.json
- tests/dummy/app/templates/components/bind-example.hbs
- tests/dummy/app/templates/components/swapping-lists-example.hbs
- tests/dummy/app/templates/components/two-lists-example.hbs
- tests/dummy/app/templates/demos/here-there.hbs
@ef4 The simplest solution was to use "native" checboxes. They are slightly more verbose, but also more performant and they don't need jquery.
> Remove jQuery, app-shims and use native checkboxes

- .travis.yml
- config/ember-try.js
This marks ember-beta as an allowed failure so that builds can pass despite the deprecations that cause both ember-canary and ember-beta to fail. Also, the current release is pointed to the wrong version, so the source in ember-release was set to the correct version to avoid this failure.
> trying to fix build

- addon/-private/transition-context.js
- addon/components/animated-beacon.js
- addon/components/animated-each.js
- addon/services/motion.js
- tests/dummy/app/components/beacon-demo.js
- tests/dummy/app/controllers/demos/beacon.js
- tests/dummy/app/templates/components/beacon-demo.hbs
- tests/dummy/app/templates/demos/beacon.hbs
- tests/integration/components/animated-beacon-test.js
This allows multiple beacons to animate simultaneously. Each beacon has a distinct `name` identifier. Beacons match using `name` which replaced `group`. Beacons are passed into the transition context and treated as sprites that you can animate to and from.
> Multiple beacons

- package.json
- yarn.lock
version 2 of ember-cli-version-checker allows ember-animated to work inside projects in a yarn workspace
> bump version of ember-cli-version-checker

- addon/-private/ember-scheduler.js
- yarn.lock
Using https://github.com/pzuraq/ember-native-class-polyfill and probably ember 3.6 there is an issue with the native class syntax and computed properties. A similar issue occurred in ember-concurrency (see https://github.com/machty/ember-concurrency/issues/261) and will be fixed in https://github.com/machty/ember-concurrency/pull/262.
I've changed the ember-scheduler to now work with the class based syntax for  the TaskProperty. As the test are still running I assume that the fix works.
> fix ember-scheduler to work with native class syntax

- addon/-private/sprite.js
- addon/components/animated-orphans.js
- copy a few more useful CSS properties 
- but don't apply line-height to orphan sprites because ugh, legacy getComputedStyles behavior
- also, appendChild before sprite.lock because trying to lock a sprite that isn't in DOM can explode (when it's an SVG element)
> tweaking orphan behaviors

- addon/components/animated-each.js
- tests/acceptance/container-demo-test.js
- tests/acceptance/if-demo-test.js
BREAKING CHANGE
500 is on the high end for certain interactions but pretty good for animations that move farther across the screen.
I eventually want to add a guide pointing to some research/best practices around keeping durations for web interactions in the 200ms - 500ms range.
> Changes default duration from 2000 to 500

- addon/-private/ember-scheduler.js
- package.json
- yarn.lock
As mentioned in #75 I've copied the approach used in ember-concurrency.
I mostly grokked what was going on, so hopefully I didn't just blindly copy unnecessary bits.
> Update TaskProperty to support Ember 3.10 decorators

- package.json
- yarn.lock
I'm not sure if there was a specific reason for pinning to the older commit, but we had an app that has this plus another addon that pulls in the latest polyfill.  The older version won, and this caused errors with the new double-colon angle bracket syntax (`<Modal::Header>`, etc)
> Upgrade ember-angle-bracket-invocation-polyfill

- addon/motions/scale.js
Seems like scale motion doesn't use provided easing option, while other motions do. It would be nice to have it also here for more seamless motion when combining scale + move.
> Shouldn't scale use easing option?

- tests/dummy/app/helpers/background-image.js
- tests/dummy/app/helpers/html-safe.js
- tests/dummy/app/pods/index/demo-3/template.hbs
- tests/dummy/app/pods/index/utils/animated-code-diff/component.js
- tests/dummy/app/pods/index/utils/animated-code-diff/template.hbs
The `htmlSafe` function can easily become a security footgun. Since the demo app exists to teach, I think it's important to exemplify the correct way to use it, even though there aren't actual security problems in the demo app since it has no authority and no private data.
The problem is that `htmlSafe` doesn't make a thing safe, it merely vouches that it's already safe.
So to use `htmlSafe` correctly, it should really be called by the same code that *makes* the string safe. In general it should be possible to look at a call to `htmlSafe` and immediately see *why* it's safe. The code that does the work of constructing the allegedly-safe string should be as close as possible to the call to `htmlSafe`.
The danger in keeping them apart is that a future refactor can easily violate the …
> Safer use of htmlSafe

- tests/dummy/app/pods/docs/beacons/template.md
The `animated-beacon` link on [this page](https://ember-animation.github.io/ember-animated/docs/beacons) worked locally, but not in the deployed context. It was missing the `ember-animated` segment in the rendered anchor url, `https://ember-animation.github.io/docs/api/components/animated-beacon`
Using the link helper might resolve this.
> docs - fix broken animated-beacon link

- addon/components/animated-orphans.js
Apparently Edge doesn't always consider HTMLCollection as iterable.
@savvymas this fixes the issue you found.
> Edge compatibility bug: "function expected"

- addon/-private/transform.js
Having no transform is different from having an identity transform, because the presence of a transform (even the identity) has side-effects like creating a new stacking context, altering the behavior of fixed positioned children, etc.
> don't serialize identity transform as "none"

- addon/-private/sprite.js
Sprites already restore their styles at the end of animation, so that nothing applied by animations can leave them permanently changed. This extends that behavior to also cover the classlist, which means it's now safe for motions to apply classes to sprites.
> reset classlist after animation

- package.json
- yarn.lock
Looks like version 2.0 ember-angle-bracket-invocation-polyfill has been released. Is this the best way to say ember-animated works with 1.3 and 2.0?
> Add new angle bracket polyfill version

- addon/-private/sprite.js
- tests/unit/sprite-test.js
#143 introduced a bug. It restores the *initial* classlist after animation, but it should restore the *final* classlist (because of course classes could be legitimately changed by ember between the two).
> fix classlist cleanup

- package.json
- yarn.lock
As used by addon-docs. Otherwise when testing without yarn.lock, ember-cli-addon-docs brings in a version of ember-data too new to work on the older end of our tested range of ember versions.
Yet another example of what's bad about having addon-docs in the dummy app. The library needs to work on ember back to 2.12. But the docs app doesn't.
> locking down ember-data version

- addon/color.js
At zero alpha we were flashing the wrong color because even though we need to not *divide* by alpha, we still need the true alpha in the output color.
> fix alpha premultiplication bug

- package.json
- yarn.lock
Updating because new versions of PowerSelect (via basic dropdown) use this version.
> fix: update element helper

- addon/transitions/fade.js
Adds a missing semicolon to [the fade transition example in the docs](https://ember-animation.github.io/ember-animated/docs/api/modules/ember-animated/transitions/fade).
> Add missing semicolon to example

- addon/-private/sprite.ts
- addon/motions/resize.ts
- yarn.lock
And switched to the new asserts type syntax that had been blocked by it.
> regenerated yarn.lock to fix @babel/parser version

- addon/-private/sprite.ts
This gives a slightly more helpful message as part of the nested animated components error.
> Add details to warning

- addon/element-remove.ts
FastBoot does not have the concept of Element, CharacterData and presumably DocumentType.  Inclusion of this polyfill thus makes FastBoot crash early.
If you want to update this PR, feel free to push on the branch.
Some further notes on this PR:
Implementation currently checks whether the either of these three entities exist and executes the polyfill for any of those that do.  Alternatively, a check on IE11 could have been placed.  Current implementation seems more flexible in the long run, though it might make phasing out the polyfill harder.
We now check whether the entity exists on the window instance.  For clarity, we'd have preferred to check for the existence of Element as a global, yet TypeScript doesn't seem to let us.
The use of Window circumvents the TypeScript error, but it …
> Fix fastboot

- package.json
- tests/fastboot/if-demo-test.js
- yarn.lock
There were bunch of fixes/improvements made in v0.3.0 and one can't use both `ember-animated` and `ember-element-helper@0.3.1` in addons versions conflicts.
> Bump ember-element-helper

- .github/workflows/nodejs.yml
- config/ember-try.js
- tests/unit/move-test.js
Noticed that CI does not run for pull requests from fork, examples #243, #221, #238.
> Run GitHub Actions CI on pull request

- addon/components/animated-value.ts
Applied `ember-template-lint`'s suggestions for [no-implicit-this](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-implicit-this.md).
> Update animated value documentation

- package.json
- yarn.lock
This change will allow apps to use the v3.0.0 release of `ember-angle-bracket-invocation-polyfill` instead of the older v1.x or v2.x series.
The requirement is widened so that ember-cli-dependency-lint is not causing issues in case apps still use addons that require the v0.1.x release.
Similar to #267 by @Turbo87.
Additionally, v3.0.0 of `ember-angle-bracket-invocation-polyfill` upgrades ember-cli-babel to v7 so another instance of ember-cli-babel@6 will go away with this upgrade.
Also v3.0.0 of `ember-angle-bracket-invocation-polyfill` drops Node < 10 support but `ember-animated` already requires Node.js v10 or above.
> Widen `ember-angle-bracket-invocation-polyfill` dependency requirement

- package.json
- yarn.lock
This change will allow apps to use the v1.0.0 release of `ember-maybe-import-regenerator` instead of the older v0.1.x series. The requirement is widened so that `ember-cli-dependency-lint` is not causing issues in case apps still use addons that require the v0.1.x release.
Extracted from #267. Thanks @Turbo87!
> Widen `ember-maybe-import-regenerator` dependency requirement

- docs/package.json
- docs/yarn.lock
- package.json
- yarn.lock
This is _BREAKING_ change as it requires the consuming app or an addon to have ember-auto-import v2.
Since that is required for Ember 4.x compatibility, this shouldn't be an issue for anyone who works toward Ember v4.
For more info see https://github.com/ef4/ember-auto-import/blob/v2.2.3/docs/upgrade-guide-2.0.md
> Update `ember-auto-import` to v2.x

- package.json
- yarn.lock
This drops support for Ember < 3.1
> Remove `ember-named-arguments-polyfill` dependency

- .github/workflows/ci.yml
There are many changes happen in Typed Ember community so disable for now and will re-enable once types stabilized and can build
> Disable TypeScript scenarios for now

- package.json
- pnpm-lock.yaml
- test-app/config/ember-try.js
- test-app/package.json
Using `dependenciesMeta.*.injected` in dev development is inconvenient as request to run `pnpm I` after every change.
> Move `dependenciesMeta.*.injected` config to `ember-try`

- addon/src/index.ts
- addon/src/transitions/fade.ts
Allows to type the argument received by the custom transition.
Closes #443 cc @kpfefferle
> Make TransitionContext type export public

- addon/src/-private/concurrency-helpers.ts
- addon/src/-private/ember-scheduler.ts
- addon/src/test-support/index.js
It looks like there is no need to use RSVP anymore and all the usages are straightforward conversion to native promise.
Would like hear from @ef4 on this just in case I'm missing something.
> Replace use of RSVP with native Promise

- addon/src/components/animated-beacon.ts
- addon/src/services/-ea-motion.ts
- test-app/tests/integration/components/animated-beacon-test.js
This addresses https://github.com/ember-animation/ember-animated/issues/225
First commit I added a failing test that just had a beacon and two animated-ifs.  That test fails like the bug describes.
After diving into the code a bit I feel that this assertion was put here in error.  As the added test shows, when multiple animated components are present the beacon will [add itself](https://github.com/ember-animation/ember-animated/blob/master/addon/src/components/animated-beacon.ts#L121) to the -ea-motion service once per new animation. 
This is because the beacons are [listening to all animations](https://github.com/ember-animation/ember-animated/blob/master/addon/src/components/animated-beacon.ts#L78).  The original authors didn't cover the case when multiple animations would start in the …
> Allow multiple beacons with the same name

- .github/workflows/ci.yml
- .github/workflows/publish-unstable.yml
- RELEASE.md
- package.json
@ef4 this setup would allow to publish to npm from CI reducing manual work.
Follows setup you did for `publish-unstable` workflow.
> Publish to npm from CI

- docs/app/styles/app.scss
- docs/app/templates/docs/rules.md
It's [a known bug](https://github.com/ember-animation/ember-animated/issues/120) that animating inline elements does not work very well.  The [recommended workaround](https://github.com/ember-animation/ember-animated/issues/124) is to use block elements instead.
This tiny PR updates two demos in the docs app to use `display: inline-block` for animated spans and avoids the visual "jump" in the animations.
> Update docs to use and recommend inline-block

- addon/src/components/animated-container.ts
just for animated-container as a probe for now, can do a full round later if there is support
> docs: modernize docs to show class based component syntax for animated-container

- addon/src/components/animated-if.ts
- addon/src/components/animated-value.ts
Follow up to [#613](https://github.com/ember-animation/ember-animated/pull/613#discussion_r1403147402)
`{{animated-if}}`, `{{animated-value}}`, `{{animated-value}}` are control flow expressions and not regular components as they expected to be used via curly braces.
We probably should implement custom curly component manager to enforce that, but that's separate.
> Glint: make predicate Positional in animated-if and animated-value signatures

- addon/package.json
- addon/src/components/animated-container.hbs
- addon/src/components/animated-container.ts
- pnpm-lock.yaml
This is a forced-hand solution to #594, and supercedes #647.
This drops support for `ember-element-helper` `<= 0.6.0` since there doesn't seem to be a good way to dynamically remove support for it during build time with ember macros at the moment. I've created an [issue]() in embroider, but I'm not sure how long it will take to have a solution.
`0.6.0` is almost two years old at this point, and continuing to support it in this library doesn't seem like it's worth it at this point. Happy to discuss!
> Drop support for ember-element-helper <= 0.6.0

- addon/src/components/animated-each.ts
- addon/src/components/animated-if.ts
- addon/src/components/animated-orphans.ts
This fixes the rendering of some code blocks, which currently [look like this](https://ember-animation.github.io/ember-animated/docs/api/components/animated-if):
When I run this PR locally:
Thanks for all the work on this!
> Fix documentation code blocks

- addon/package.json
This is fixing imports of `ember-animated/test-support` not resolving correctly. Order in `package.json#exports`  is relevant, so the catch-all rule should come last. Also, for TS projects still using legacy `moduleResolution`, `typesVersions` should cover the index-module.
> Fix test-support exports

- addon/package.json
Should allow usage of `@ember/test-helpers` @ v4
> Widen peer range for peer, @ember/test-helpers

- addon/src/components/animated-each.ts
- addon/src/components/animated-if.ts
- It seems like when there is no empty line before code example fencing, the markdown parser won't interpret the code block as code block.
- This is locally reproducible on v1.1.4 tag.
- Locally v2.0.0 works for me, but it broken in online version, but I figured this change could not hurt in both versions.
Relates to: #691 
Fixes: #689
> fix: Make it so that code examples render correctly v2.x/master

- addon/src/components/animated-each.ts
- addon/src/components/animated-if.ts
- addon/src/components/animated-orphans.ts
- It seems like when there is no empty line before code example fencing, the markdown parser won't interpret the code block as code block.
- This is locally reproducible on v1.1.4 tag.
- Locally v2.0.0 works for me, but it broken in online version, but I figured this change could not hurt in both versions.
Relates to: #690 
Fixes: #689
> fix: Make it so that code examples render correctly v1.x

- addon/package.json
is extraneous, and the embroider/auto-import infra know where to get ember-source from.
It's not _wrong_ to include, but it requires folks' manage their deps correctly -- so we can be a little more forgiving to maintainers by just omitting this.
From PR descriptions elsewhere:
- ember-source: removed because the embroider / auto-import know what we intend - it's not bad to have if someone manages their dep graph correctly, which is easier with pnpm, but not everyone gets it right, and folks have a hard time tracking down errors
- @glimmer/tracking removed because it's a real package, but one we don't want to use. This comes up in embroider/vite where the presence of real packages always takes precedence over virtual packages. This is actually problematic because it can break reactivity in …
> Removed unneeded peer declaration
