ember-animation/ember-animated

addon/motions/opacity.js
addon/sprite.js
tests/dummy/app/controllers/hero/index.js
tests/dummy/app/styles/app.css

to manipulate opacity of sprites.

Add Opacity motion

---

README.md
package.json

Cleanup package.json and README

---

tests/acceptance/orphan-test.js
tests/dummy/app/components/each-example.js
tests/dummy/app/controllers/demos/nested.js
tests/dummy/app/controllers/demos/orphan.js
tests/dummy/app/templates/demos/orphan.hbs

- and adding test coverage
- and fixing tests on headless chrome (where there is no valid outerWidth)

fixing orphan demo

---

tests/dummy/app/templates/demos/index.hbs

I think that this PR https://github.com/ember-animation/ember-animated/pull/20/ broke the index page links, so a small fix.

Fixes the dummy app demo links index.

---

tests/helpers/assertions.js
tests/integration/components/animated-container-test.js
tests/integration/components/animated-each-test.js
tests/integration/components/animated-if-test.js
tests/integration/components/animated-orphans-test.js
tests/integration/components/animated-value-test.js
tests/unit/motion-test.js
tests/unit/move-test.js
tests/unit/opacity-test.js
tests/unit/sprite-test.js
tests/unit/transform-test.js

Just some cleaning before removing jquery from addon code.
There was A LOT

Remove all jquery usages in tests

---

addon/components/animated-each.js
addon/templates/components/animated-each.hbs
tests/integration/components/animated-each-test.js

Yield index in animate-each

---

tests/dummy/app/templates/components/swapping-lists-example.hbs
tests/dummy/app/templates/demos/here-there.hbs

Ref. https://github.com/ember-animation/ember-animated/issues/31 https://github.com/ember-animation/ember-animated/pull/30

Remove jQuery based checkboxes from dummy app

---

.template-lintrc.js
addon/templates/components/animated-each.hbs
tests/dummy/app/templates/components/between-components.hbs
tests/dummy/app/templates/components/full-log-table.hbs
tests/dummy/app/templates/components/sprites-example.hbs
tests/dummy/app/templates/components/transition-log-table.hbs
tests/dummy/app/templates/docs.hbs
tests/dummy/app/templates/index.hbs
tests/dummy/app/templates/not-found.hbs

fixes template lint issues related to quotes.
partial fix for #52

Fix template lint issues

---

.template-lintrc.js
.travis.yml
addon/templates/components/animated-each.hbs
addon/templates/components/animated-value.hbs
config/ember-try.js
tests/dummy/app/templates/components/animated-text.hbs
tests/dummy/app/templates/components/between-components.hbs
tests/dummy/app/templates/components/between-swap-lists-example.hbs
tests/dummy/app/templates/components/bind-example.hbs
tests/dummy/app/templates/components/container-demo.hbs
tests/dummy/app/templates/components/each-demo.hbs
tests/dummy/app/templates/components/full-log-table.hbs
tests/dummy/app/templates/components/if-demo.hbs
tests/dummy/app/templates/components/moving-word.hbs
tests/dummy/app/templates/components/opacity-demo.hbs
tests/dummy/app/templates/components/rules-example.hbs
tests/dummy/app/templates/components/sprites-example.hbs
tests/dummy/app/templates/components/svg-example.hbs
tests/dummy/app/templates/components/transition-log-table.hbs
tests/dummy/app/templates/components/transitions-example.hbs
tests/dummy/app/templates/components/transitions-moveover.hbs
tests/dummy/app/templates/components/value-demo.hbs
tests/dummy/app/templates/demos/beacon.hbs
tests/dummy/app/templates/demos/direct-style.hbs
tests/dummy/app/templates/demos/hero/index.hbs
tests/dummy/app/templates/demos/svg.hbs
tests/dummy/app/templates/docs/between/index.hbs
yarn.lock

This PR fixes template lint issues related to `block-indentation`.
partial fix for #52

Fix template lint issues / block-indentation

---

package.json
tests/dummy/app/styles/app.css
tests/dummy/app/templates/components/index/index-content.md
tests/dummy/app/templates/index.hbs
yarn.lock

You can now give AddonDocs a brand color, and I really like the shade of pink you chose for liquid-fire :)

Set brand color for docs

---

addon/templates/components/animated-each.hbs

Eat animated-each's whitespace

---

tests/dummy/app/styles/app.css

Fix layout issue with Data-Dependent Rules example

---

CONTRIBUTING.md

This project uses yarn, not npm

CONTRIBUTING.md - refer to yarn instead of npm

---

addon/components/animated-each.js

When a transition is interrupted, any removed sprites that didn't run a motion during that transition get instantly removed before the next transition begins. This lets us garbage collect old sprites -- to keep them around you need to keep applying motions to them.
But there was a race condition in which two rapid changes could come in before your transition even has a chance to start, in which case all your removed sprites would get deleted before you saw them.

fix a race condition

---

addon/-private/sprite.js

This fixes #125.
Instead of using `offsetWidth` and `offsetHeight`, I reordered slightly so that we have bounds and cumulative transforms instead. This gives us full subpixel resolution.

fix offsetWidth rounding

---

addon/components/animated-container.js
addon/templates/components/animated-container.hbs
package.json
tests/integration/components/animated-container-test.js
yarn.lock

A PR for https://github.com/ember-animation/ember-animated/issues/138

Container tag

---

addon/-private/sprite.js

Co-authored-by: Will Bagby <bagsbee@gmail.com>
Co-authored-by: Burcu Noyan <burieberry@users.noreply.github.com>

track border-radius properties

---

addon-test-support/index.js
addon/-private/sprite.js
addon/box-shadow.js
addon/color.js
addon/motions/adjust-color.js
addon/motions/box-shadow.js
tests/dummy/app/pods/demos/color-and-shadow/controller.js
tests/dummy/app/pods/demos/color-and-shadow/template.hbs
tests/dummy/app/router.js
tests/unit/adjust-color-test.js
tests/unit/box-shadow-parser-test.js

This adds a boxShadow motion that interpolates CSS box-shadow. It follows the CSS spec.

Box shadow motion

---

addon/-private/sprite.ts
docs/app/pods/index/demo-3/component.js

Demo 3 is broken. #107 didn't include the fixes in this PR. I'd be happy to close this one if these would be moved to #107

Fix property name in demo and typo in error

---

addon/-private/bounds.ts
addon/domrect-polyfill.ts

polyfill DOMRect on browsers that don't have it

---

addon/-private/tween.ts
tests/unit/move-test.js

This pull request removes easing limitation for values above 1 and adds test for under- and overshooting.
That resolves #198 - full explanation of the problem can be found there.

Overshooting

---

package.json
yarn.lock

Somehow a FastBoot test was added in #221 but necessary packages were not added.

Add missing `ember-cli-fastboot` and `ember-cli-fastboot-testing` devDependencies

---

test-app/app/adapters/person.js
test-app/app/models/person.js
test-app/app/routes/demos/hero/detail.js
test-app/app/routes/demos/hero/index.js
test-app/app/styles/app.scss

These comments were leftovers from when the test app was used for documentation site

Remove unused BEGIN-SNIPPET/END-SNIPPET from test-app

---

addon/package.json

Add RSVP as a peerDependency

---

addon/package.json

This reverts commit f24c5862dede0a71d43b42ad9320e972fc68fa0d.
https://github.com/ember-animation/ember-animated/issues/451#issuecomment-1100678251

Revert "Add RSVP as a peerDependency"

---

addon/package.json

Fix types for modern TS

---

addon/package.json
addon/src/components/animated-beacon.ts
addon/src/components/animated-container.hbs
addon/src/components/animated-container.ts
addon/src/components/animated-each.ts
addon/src/components/animated-if.ts
addon/src/components/animated-orphans.ts
addon/src/components/animated-value.ts
addon/src/components/ea-list-element.ts
addon/src/template-registry.ts
addon/unpublished-development-types/index.d.ts
docs/app/templates/docs/index.md
package.json
pnpm-lock.yaml

This work is based on [`@gavant/glint-template-types`](https://github.com/Gavant/glint-template-types). Credit to @wagenet and @bakerac4 for their effort in that package

Introduce Glint types

---

.github/workflows/ci.yml
README.md
test-app/config/ember-try.js

as 4.8 and 4.12 are LTS versions

Add 4.8 and 4.12 ember-try scenarios

---

addon/package.json

Glint ember-animated/template-registry not found

---

addon/package.json
addon/src/components/animated-container.ts
addon/src/components/animated-each.ts
addon/src/components/animated-orphans.ts
addon/src/services/-ea-motion.ts
docs/package.json
pnpm-lock.yaml
test-app/package.json

This is pending prettier fix https://github.com/prettier/prettier/issues/16429 as lint currently fails

Add parentheses for decorators to prevent TS1497 error.
